extends GameObjectCounted

class_name GameboardConstants
#LAYERS
const GROUND_LAYER = 0
const BUILD_LAYER = 1
const BLOCK_LAYER = 2
const SELECTION_LAYER = 3
const TURRET_RANGE_PREVIEW_LAYER = 4

#TILES
const TURRET_RANGE_PREVIEW_TILE_ID = 0
const LEGAL_PLACEMENT_TILE_ID = 1
const ILLEGAL_PLACEMENT_TILE_ID = 2
const BASE_PREVIEW_TILE_ID = 3
const GROUND_TILE_ID = 4

#ENTITIES
const PLAYER_BASE_TILE_ID = 5
const SPAWNER_TILE_ID = 6
const WALL_TILE_ID = 7

#BUILD
const ALL_BUILD_TILE_ID = 8

#TYPES
const WALL_TYPE = "WALL"
const GROUND_TYPE = "GROUND"
const BASE_GREY_TYPE = "BASE_GREY"
const SPAWNER_TYPE = "SPAWNER"
const PLAYER_BASE_TYPE = "PLAYER_BASE"

const ALL_BUILD_TYPE = "ALL_BUILD"
