extends Node

class_name GameboardConstants
#LAYERS
const BLOCK_LAYER = 0
const GROUND_LAYER = 1
const SELECTION_LAYER = 2
const TURRET_RANGE_PREVIEW_LAYER = 3

#TILES
const TURRET_RANGE_PREVIEW_TILE_ID = 0
const LEGAL_PLACEMENT_TILE_ID = 1
const ILLEGAL_PLACEMENT_TILE_ID = 2
const BASE_PREVIEW_TILE_ID = 3
const GROUND_TILE_ID = 4

const PLAYER_BASE_TILE_ID = 5
const SPAWNER_TILE_ID = 6
const WALL_TILE_ID = 7
